### ISSUE TITLE
README ommissions/corrections

### ISSUE THREAD

**Issue by pdavidow** [input-output-hk/plutus-use-cases#61]
https://github.com/input-output-hk/plutus-use-cases/blob/Dquadrant/stablecoin/starter/Dquadrant/stable-coin/README.md
Sub-steps under 6 (_Start nix shell from plutus folder with command_ `nix-shell`):

- After cloning repo, need to add step: Load correct branch (`Dquadrant/stablecoin/starter`)

- Step 4:
  `curl -s http://localhost/api/new/contract/instances | jq`
   should be 
   `curl -s http://localhost:8080/api/new/contract/instances | jq`
   
- `export ORACLE_ID = <Contract Id from above step>`
   should be changed to show no spaces around equal sign
   `export ORACLE_ID=<Contract Id from above step>`
   (same issue with `export INSTANCE_ID = ` etc)
   
 - Step 10 _Redeem reserve token_ has wrong endpoint (`redeemStableCoin`).  Should be`redeemReserveCoin`

**Comment by nabinpkl** [comment]
Thanks for the feedback highly appreciated.
